### PR TITLE
Re-structure of RxTimelane

### PR DESCRIPTION
**Pull request by KarimEbrahemAbdelaziz**
# What is this PR about ?
- This PR is Re-Structure of folders and files to match the same as `TimelaneCombine` structure.

### CODE REVIEW

**Comment by icanzilb** [comment]
This looks great, thank you! It looks like the demo app was deleted though? It was in the "Example" sub-folder .. do you think it's better to call the directory "DemoApp" or something more clear?

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb I don't think so. As it's not an example for the library.
We could add an example to demonstrate the library and name it `Example` or `Demo`. What do you think?

**Comment by icanzilb** [comment]
I'm not sure what you mean - the `Example` folder that you deleted in this PR was an iOS app that demonstrates how to use RxTimelane.

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb Ooouch
Oki, I will update the PR now. Wait a minute 😅

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb I added the example project as new scheme, please check it.
It's much cleaner way to add an example to library, hope you found it good 😄💪🏻

**Comment by icanzilb** [comment]
hi @KarimEbrahemAbdelaziz, thanks for the change but I have another issue with it. Now the demo app requires the users to use Carthage, while the original demo app worked in Xcode without any additional requirements.

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb Yup I see, but do you have any suggestions to make it better ?!

**Comment by icanzilb** [comment]
Yes, I'm sorry - I think the best approach would be to bring the "Example" folder as it was, keep all the other changes as you have them right now.

**Comment by icanzilb** [comment]
I mean: best to move the demo app as it was in the "Example" folder and remove the extra scheme in the RxTimelene.xcproj

**Comment by KarimEbrahemAbdelaziz** [comment]
Ummm what about including `Carthage` folder ?! It will keep the example scheme works and there will be no need for Carthage.

**Comment by KarimEbrahemAbdelaziz** [comment]
> Yes, I'm sorry - I think the best approach would be to bring the "Example" folder as it was, keep all the other changes as you have them right now.

It won't change any thing if it's another project or another scheme, the same problem will remain (User must have Carthage to run the Example).

**Comment by icanzilb** [comment]
It feels there is some kind of misunderstanding. Check out `master` and open the project inside the "Example" folder - you do not need Carthage to run the project.

**Comment by KarimEbrahemAbdelaziz** [comment]
> It feels there is some kind of misunderstanding. Check out `master` and open the project inside the "Example" folder - you do not need Carthage to run the project.

I think yes 😄
You added the dependencies (RxSwift and TimelanCore) for the `Example` through SPM and I just added them to the Example Scheme through Carthage. That's why you see a difference.

I could add them to the example using SPM too, what do you think ?

**Comment by icanzilb** [comment]
Yes please, SPM is built into Xcode and Carthage is a 3rd party dependency manager.

**Comment by KarimEbrahemAbdelaziz** [comment]
> Yes please, SPM is built into Xcode and Carthage is a 3rd party dependency manager.

Done. Please check it now ☺️💪🏻

**Comment by icanzilb** [comment]
Oh yeah, I like this - it's definitely better than before :) Merging that in, thanks and sorry if it was a bit unclear input there

**Pull request merged**
