### PR TITLE
Add Carthage support for RxTimelane

### PR DESCRIPTION
**Pull request by mRs-**
I've added Carthage support for RxTimelane.

ToDo:
1. Merge https://github.com/icanzilb/TimelaneCore/pull/4
2. Check this out this branch and resolve the package for swiftpm
3. Merge this pull request
4. create 1.0.1 versions on RxTimelane and TimelaneCore

Everything should work fine then :)

### CODE REVIEW

**Comment by icanzilb** [comment]
This looks great @mRs- , is there any ongoing maintenance work that this change requires?

**Comment by mRs-** [comment]
The ToDo List is more for you as the owner of this repository. My changes are all finished 😀

**Comment by icanzilb** [comment]
My question had a different sentiment - I don't use Carthage myself (or at least not regularly) so I'm not quite sure if adding support for Carthage is a one time change or as the library evolves over time some changes will need to be made to the Carthage compatibility. (I vaguely remember users complaining sometimes that "Carthage support was broken" on some of my other repos so I stopped supporting Carthage whatsoever). I'm just double checking what I'm committing to if I merge this PR

**Comment by mRs-** [comment]
As long there is a shared framework path in the xcodeproj file everything should be fine. When there is a new RxSwift Version a bump in the Cartfile must be done.

Currently I'm using Carthage too and fixing problems like this should be easy for every dev in the future. The changes are most of the time really simple and everyone with a bit Carthage experience can do it.

**Comment by icanzilb** [comment]
So I came around to testing this PR and here's the result. 

 - The TimelaneCore PR is merged
 - I checked out you branch
 - I ran `carthage update`:

```
*** Checking out RxSwift at "5.0.1"
*** Checking out TimelaneCore at "1.0.1"
Marins-MBP:RxTimelane marin$ carthage build
*** xcodebuild output can be found in /var/folders/b0/92hzk1lj6w1_k_qrm0zxpl_80000gn/T/carthage-xcodebuild.F7ormy.log
*** Downloading RxSwift.framework binary at "ShaiTheBravest"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)."

    Falling back to building from the source
*** Building scheme "RxBlocking" in Rx.xcworkspace
*** Building scheme "RxSwift" in Rx.xcworkspace
*** Building scheme "RxRelay" in Rx.xcworkspace
*** Building scheme "RxCocoa" in Rx.xcworkspace
*** Building scheme "RxTest" in Rx.xcworkspace
*** Skipped building TimelaneCore due to the error:
Dependency "TimelaneCore" has no shared framework schemes
```

In the Carthage sub-folder there are frameworks for all platforms for all the rx libraries but no .framework for Timelane.

How does it work for you? I reckon we need some instructions in the README as well - not sure if what I did are the expected steps

**Comment by mRs-** [comment]
I forgot to push my local changes for TimelaneCore 🤦‍♂

**Comment by icanzilb** [comment]
It happens, just ping me when you push everything up

**Comment by icanzilb** [comment]
Another PR added Carthage support for TimelaneCore so this one is unblocked - thank you!

**Comment by mRs-** [comment]
Nice!

**Pull request merged**
